#define PHONG
uniform vec3 diffuse;
uniform vec3 emissive;
uniform vec3 specular;
uniform float shininess;
uniform float time;
uniform float opacity;
uniform vec2 waterfalls;
varying vec2 vUv;
// chunk(common);
// chunk(packing);
// chunk(color_pars_fragment);
// chunk(uv_pars_fragment);
// chunk(uv2_pars_fragment);
// chunk(map_pars_fragment);
// chunk(alphamap_pars_fragment);
// chunk(aomap_pars_fragment);
// chunk(lightmap_pars_fragment);
// chunk(emissivemap_pars_fragment);
// chunk(envmap_pars_fragment);
// chunk(gradientmap_pars_fragment);
// chunk(fog_pars_fragment);
// chunk(bsdfs);
// chunk(lights_pars);
// chunk(lights_phong_pars_fragment);
// chunk(shadowmap_pars_fragment);
// chunk(bumpmap_pars_fragment);
// chunk(normalmap_pars_fragment);
// chunk(specularmap_pars_fragment);
// chunk(logdepthbuf_pars_fragment);
// chunk(clipping_planes_pars_fragment);
void main() {
  // chunk(clipping_planes_fragment);
  vec4 diffuseColor = vec4( diffuse, opacity );
  ReflectedLight reflectedLight = ReflectedLight( vec3( 0.0 ), vec3( 0.0 ), vec3( 0.0 ), vec3( 0.0 ) );
  vec3 totalEmissiveRadiance = emissive;
  // chunk(logdepthbuf_fragment);
  // chunk(map_fragment);
  // chunk(color_fragment);
  // chunk(alphamap_fragment);
  // chunk(alphatest_fragment);
  // chunk(specularmap_fragment);
  // chunk(normal_flip);
  // chunk(normal_fragment);
  // chunk(emissivemap_fragment);
  // chunk(lights_phong_fragment);
  // chunk(lights_template);
  // chunk(aomap_fragment);
  vec3 outgoingLight = reflectedLight.directDiffuse + reflectedLight.indirectDiffuse + reflectedLight.directSpecular + reflectedLight.indirectSpecular + totalEmissiveRadiance;
  // chunk(envmap_fragment);
  gl_FragColor = vec4( outgoingLight, diffuseColor.a );
  // chunk(premultiplied_alpha_fragment);
  // chunk(tonemapping_fragment);
  // chunk(encodings_fragment);
  // chunk(fog_fragment);
  float dist = 1.0 - min(distance(vec2(waterfalls.x, waterfalls.y), vUv), 0.05) / 0.05;
  gl_FragColor.rgb += vec3(floor(cos(dist * 10.0 + time * 100.0) * -2.0 * dist * 10.0) / 10.0 * 0.1);
  gl_FragColor.a *= 0.5;
}
